/*
 yerbajs - simple javascript data management
  @copyright 2014 Kevin von Flotow <vonflow@gmail.com>
  @license MIT License <http://opensource.org/licenses/MIT>
*/
(function(){var l=function(){function d(){}var h=Object.create||function(){function a(){}return function(c){if(1!=arguments.length)throw Error("Object.create implementation only accepts one parameter.");a.prototype=c;return new a}}();d.prototype={genUID:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var c=16*Math.random()|0;return("x"===a?c:c&3|8).toString(16)})},isFunction:function(a){return"[object Function]"===Object.prototype.toString.call(a)},isString:function(a){return"string"===
typeof a||a instanceof String},isNumber:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},isObject:function(a){return a===Object(a)&&"[object Array]"!==Object.prototype.toString.call(a)},isArray:Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)},toArray:function(a){for(var c=[],d=0,f=a.length;d<f;++d)c.push(a[d]);return c},extend:function(){var a=arguments;if(0===a.length)return!1;for(var c=0,d=a.length,f=h(a[0]);c<d;c++)for(var g in a[c])f[g]=a[c][g];return f}};
return new d}.call(this);(function(d,h){function a(b){if(this._init)return this._init(b)}function c(b){b=b||[];this.indices={_id:{}};for(var a=this.length=this.lastUpdate=0,e=b.length;a<e;a++)this.add(b[a])}function m(b){if(!b)return!1;var a=h,e={},c=function(b){};isFunction(b)?c=b:(a="undefined"!==typeof b.query?b.query:a,e=b.opts||e,c=b.done||c);e.caseSensitive="undefined"!==typeof e.caseSensitive?e.caseSensitive:!0;e.limit="undefined"!==typeof e.limit&&d.isNumber(e.limit)?e.limit|0:0;var f=[];
this.each(function(b,c){var g=0,h=0;if(d.isString(a)||d.isNumber(a))g=1,"undefined"!==typeof c.data&&c.data==a&&(h=1);else for(var k in a)c.hasOwnProperty(k)&&(e.caseSensitive&&c[k]===a[k]||!e.caseSensitive&&c[k].toLowerCase()===a[k].toLowerCase())&&h++,g++;if(h===g&&(f.push(c),0<e.limit&&f.length>=e.limit))return!1});c.call(this,f);return this}function f(){for(var b=0,a=arguments.length;b<a;++b)this.addOne(arguments[b]);return this}function g(){var b=Array.prototype.pop.call(this);this._reIndex();
return b}function n(){for(var b=0,a=this.length;b<a;++b)delete this[b];return this._init()}function p(){for(var b=this.length,a,c;0<--b;)a=Math.random()*(b+1)|0,c=this[a],this[a]=this[b],this[b]=c;return this}var l=Date.prototype.toISOString?"toISOString":"getTime";a.prototype={_init:c,brew:c,_setLastUpdate:function(){this.lastUpdate=(new Date)[l]()},_generateUID:function(){for(var b=d.genUID();this.get(b);b=d.genUID());return b},_reIndex:function(){this.indices={_id:{}};this.each(function(b,a){this.indices._id[a._id]=
b});return this},each:function(b){for(var a=0,c=this.length;a<c;++a){var d=b.call(this,a,this[a]);if(!d&&"undefined"!==typeof d)break}return this},get:function(b){return this.indices._id.hasOwnProperty(b)?this[this.indices._id[b]]:!1},find:m,bombilla:m,shuffle:p,stir:p,clone:function(){return this.slice(0)},random:function(){var b=this.clone().shuffle();return b[Math.random()*b.length|0]},addOne:function(b){b={data:b};b._id=b.data._id||this._generateUID();if(this.indices._id.hasOwnProperty(b._id))this[this.indices._id[b._id]]=
b;else{var a=this.length++;this[a]=b;this.indices._id[b._id]=a}this._setLastUpdate();return this},add:f,pour:f,toArray:function(){return d.toArray(this)},slice:function(b,c){return new a(Array.prototype.slice.call(this,b,c))},pop:g,sip:g,shift:function(){var a=Array.prototype.shift.call(this);this._reIndex();return a},flush:n,spill:n,extend:function(){for(var b=0,c=arguments.length;b<c;++b)console.log(a.isYerba(arguments[b])),"yerba"===typeof arguments[b]&&console.log("yerbaaa")}};a.isYerba=function(b){return b instanceof
a};a._$=d;if("undefined"!==typeof module&&module.exports)module.exports=a;else if(window)window.yerba=a;else return a}).call(this,l,void 0)}).call(this);
