/*
 yerbajs - simple javascript data management
  @copyright 2014 Kevin von Flotow <vonflow@gmail.com>
  @license MIT License <http://opensource.org/licenses/MIT>
*/
(function(){(function(f,b){function e(){}function c(a){if(this._init)return this._init(a)}var h=Date.prototype.toISOString?"toISOString":"getTime",g={};e.prototype={_$:f,logLevel:3,storage:b,_generateId:function(){for(var a=f.genId(8);g.hasOwnProperty(a);)a=f.genId(8);return a},yerbas:function(){return g},brew:function(a){a=new c(a);var d=this._generateId();a._yerbaId=d;return g[d]=a},isYerba:function(a){return a instanceof c},set:function(a){for(var d in a)c.hasOwnProperty(d)&&(this[d]=a[d])}};c.prototype=
{_init:function(a){a=a||[];this.opts={idName:"_id",idLength:8};this._yerbaId=null;this.length=this.lastUpdate=0;this._resetIndices();"undefined"!==typeof a&&this.add(a);this.log({3:"yerba initialized",4:JSON.stringify(this)});return this},_setLastUpdate:function(){this.lastUpdate=(new Date)[h]()},_generateId:function(){for(var a=f.genId(this.opts.idLength);this.indices[this.opts.idName].hasOwnProperty(a);)a=f.genId(this.opts.idLength);return a},_resetIndices:function(){this.indices={};this.indices[this.opts.idName]=
{};this.each(function(a,d){this.indices[this.opts.idName][d[this.opts.idName]]=a});return this},log:function(a){for(var d in a)d<=c.logLevel&&console.log("yerba:"+d+":> "+a[d]);return this},set:function(a){for(var d in a)switch(this.opts.hasOwnProperty(d)&&(this.opts[d]=a[d]),d){case "idName":this._resetIndices()}},each:function(a){for(var d=0,b=this.length;d<b;++d){var c=a.call(this,d,this[d]);if(!c&&"undefined"!==typeof c)break}return this},getDataById:function(a){return this.indices[this.opts.idName].hasOwnProperty(a)?
this[this.indices[this.opts.idName][a]]:!1},find:function(a){if(!a)return!1;var d=b,c={},e=function(a){};f.isFunction(a)?e=a:(d="undefined"!==typeof a.query?a.query:d,c=a.opts||c,e=a.done||e);c.caseSensitive="undefined"!==typeof c.caseSensitive?c.caseSensitive:!0;c.limit="undefined"!==typeof c.limit&&f.isNumber(c.limit)?c.limit|0:0;var g=[];this.each(function(a,b){var e=0,h=0;if(f.isString(d)||f.isNumber(d))e=1,"undefined"!==typeof b.data&&b.data==d&&(h=1);else for(var k in d)b.data.hasOwnProperty(k)&&
(c.caseSensitive&&b.data[k]===d[k]||!c.caseSensitive&&b.data[k].toLowerCase()===d[k].toLowerCase())&&h++,e++;if(h===e&&(g.push(b),0<c.limit&&g.length>=c.limit))return!1});e.call(this,g);return this},shuffle:function(){for(var a=this.length,d,b;0<--a;)d=Math.random()*(a+1)|0,b=this[d],this[d]=this[a],this[a]=b;this._resetIndices();return this},clone:function(){return this.slice(0)},random:function(){var a=this.clone().shuffle();return a[Math.random()*a.length|0]},addOne:function(a){a={data:a};a[this.opts.idName]=
a.data[this.opts.idName]||this._generateId();if(this.indices[this.opts.idName].hasOwnProperty(a[this.opts.idName]))this[this.indices[this.opts.idName][a[this.opts.idName]]]=a;else{var d=this.length++;this[d]=a;this.indices[this.opts.idName][a[this.opts.idName]]=d}this._setLastUpdate();return this},add:function(a){f.isArray(a)||(a=[a]);for(var d=0,b=a.length;d<b;++d)this.addOne(a[d]);return this},toArray:function(){return f.toArray(this)},slice:function(a,b){return new c(Array.prototype.slice.call(this,
a,b))},pop:function(){var a=Array.prototype.pop.call(this);this._resetIndices();return a},shift:function(){var a=Array.prototype.shift.call(this);this._resetIndices();return a},flush:function(){this.each(function(a,b){delete this[a]});this._resetIndices();this.length=this.lastUpdate=0;return this},merge:function(a){c.isYerba(a)&&(a=[a]);for(var b=[],e=0,f=a.length;e<f;++e)c.isYerba(a[e])&&a[e].each(function(a,c){b.push(c.data)});this.add(b);return this}};f.extend(c,e.prototype,{fn:c.prototype});"undefined"!==
typeof module&&module.exports?module.exports=c:"undefined"!==typeof window&&(window.yerba=c)})(new (function(){function f(){this._init()}f.prototype={_init:function(){},isFunction:function(b){return"[object Function]"===Object.prototype.toString.call(b)},isString:function(b){return"string"===typeof b||b instanceof String},isNumber:function(b){return!isNaN(parseFloat(b))&&isFinite(b)},isObject:function(b){return b===Object(b)&&"[object Array]"!==Object.prototype.toString.call(b)},isArray:Array.isArray||
function(b){return"[object Array]"===Object.prototype.toString.call(b)},toArray:function(b){for(var e=[],c=0,f=b.length;c<f;++c)e.push(b[c]);return e},extend:function(){var b=this.toArray(arguments);1===b.length&&this.isArray(b[0])&&(b=b[0]);var e=b[0]||[];if(2<=b.length)for(var c=1,f=b.length;c<f;++c)if("undefined"!==typeof b[c])for(var g in b[c])"undefined"!==typeof g&&(e[g]=b[c][g]);return e},genId:function(b){var e=0;b=(b||16)-1;for(var c=(26*Math.random()+10|0).toString(36);e<b;++e){var f=36*
Math.random()|0,g=f.toString(36);9<f&&1===(Math.random()+0.3|0)&&(g=g.toUpperCase());c+=g}return c}};return f}()),void 0)})();
