/*
 yerbajs - simple javascript data management
  @copyright 2014 Kevin von Flotow <vonflow@gmail.com>
  @license MIT License <http://opensource.org/licenses/MIT>
*/
(function(){(function(f,b){function c(a){if(this._init)return this._init(a)}var e=Date.prototype.toISOString?"toISOString":"getTime";f.extend(c,{_$:f,logLevel:3,brew:function(a){return new c(a)},isYerba:function(a){return a instanceof c},set:function(a,d){c.hasOwnProperty(a)&&(this[a]=d)}});c.prototype={_init:function(a){a=a||[];this.indices={_id:{}};this.length=this.lastUpdate=0;this.add(a);3>=c.logLevel?this.log(3,"yerba initialized"):this.log(4,JSON.stringify(this));return this},brew:function(a){return this._init(a)},
_setLastUpdate:function(){this.lastUpdate=(new Date)[e]()},_generateUID:function(){for(var a=f.genUID();this.indices._id.hasOwnProperty(a);)a=f.genUID();return a},_reIndex:function(){this.indices={_id:{}};this.each(function(a,d){this.indices._id[d._id]=a});return this},log:function(a,d){return a<=c.logLevel?console.log("yerba:"+a+":> "+d):!1},set:function(a,d){f.hasOwnProperty(a)&&(f[a]=d);this.hasOwnProperty(a)&&(this[a]=d)},each:function(a){for(var d=0,b=this.length;d<b;++d){var c=a.call(this,d,
this[d]);if(!c&&"undefined"!==typeof c)break}return this},get:function(a){return this.indices._id.hasOwnProperty(a)?this[this.indices._id[a]]:!1},find:function(a){if(!a)return!1;var d=b,c={},e=function(a){};isFunction(a)?e=a:(d="undefined"!==typeof a.query?a.query:d,c=a.opts||c,e=a.done||e);c.caseSensitive="undefined"!==typeof c.caseSensitive?c.caseSensitive:!0;c.limit="undefined"!==typeof c.limit&&f.isNumber(c.limit)?c.limit|0:0;var h=[];this.each(function(a,b){var e=0,k=0;if(f.isString(d)||f.isNumber(d))e=
1,"undefined"!==typeof b.data&&b.data==d&&(k=1);else for(var g in d)b.hasOwnProperty(g)&&(c.caseSensitive&&b[g]===d[g]||!c.caseSensitive&&b[g].toLowerCase()===d[g].toLowerCase())&&k++,e++;if(k===e&&(h.push(b),0<c.limit&&h.length>=c.limit))return!1});e.call(this,h);return this},shuffle:function(){for(var a=this.length,d,b;0<--a;)d=Math.random()*(a+1)|0,b=this[d],this[d]=this[a],this[a]=b;return this},clone:function(){return this.slice(0)},random:function(){var a=this.clone().shuffle();return a[Math.random()*
a.length|0]},addOne:function(a){a={data:a};a._id=a.data._id||this._generateUID();if(this.indices._id.hasOwnProperty(a._id))this[this.indices._id[a._id]]=a;else{var d=this.length++;this[d]=a;this.indices._id[a._id]=d}this._setLastUpdate();return this},add:function(a){for(var d=0,b=a.length;d<b;++d)this.addOne(a[d]);return this},toArray:function(){return f.toArray(this)},slice:function(a,b){return new c(Array.prototype.slice.call(this,a,b))},pop:function(){var a=Array.prototype.pop.call(this);this._reIndex();
return a},shift:function(){var a=Array.prototype.shift.call(this);this._reIndex();return a},flush:function(){this.each(function(a,b){delete this[a]});return this._init()},merge:function(a){c.isYerba(a)&&(a=[a]);for(var b=[],e=0,f=a.length;e<f;++e)c.isYerba(a[e])&&a[e].each(function(a,c){b.push(c.data)});this.add(b);return this}};if("undefined"!==typeof module&&module.exports)module.exports=c;else if(window)window.yerba=c;else return c})(new (function(){function f(){this._init()}f.prototype={_init:function(){this.logging=
!0},isFunction:function(b){return"[object Function]"===Object.prototype.toString.call(b)},isString:function(b){return"string"===typeof b||b instanceof String},isNumber:function(b){return!isNaN(parseFloat(b))&&isFinite(b)},isObject:function(b){return b===Object(b)&&"[object Array]"!==Object.prototype.toString.call(b)},isArray:Array.isArray||function(b){return"[object Array]"===Object.prototype.toString.call(b)},toArray:function(b){for(var c=[],e=0,a=b.length;e<a;++e)c.push(b[e]);return c},extend:function(){var b=
this.toArray(arguments),c=b[0]||[];if(2<=b.length)for(var b=b.slice(1),e=0,a=b.length;e<a;++e)if(void 0!==b[e])for(var d in b[e])void 0!==d&&(c[d]=b[e][d])},genUID:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(b){var c=16*Math.random()|0;return("x"===b?c:c&3|8).toString(16)})}};return f}()),void 0)})();
